name: nodejs-t
#名字，随便取
on:
  push:
    branches: main
  workflow_dispatch:
#触发条件，常用的有特定分支的代码提交，点击按钮，标记特定标签。这里采用了前两种。
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        ref: main
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: ahkworld/nodejs-t
        username: ahkworld
        password: ${{ secrets.DOCKER_PASSWORD }}
        snapshot: true
        dockerfile: Dockerfile
        tags: "main"
